In [26]:
import numpy as np

In [27]:
# array 만들기
array_1d = np.array([1,2,3,4,5])
array_2d = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [28]:
print(array_1d)
print(array_1d.shape)

[1 2 3 4 5]
(5,)


In [29]:
print(array_2d)
print(array_2d.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [30]:
empty_array_1d = np.zeros(5)
print(empty_array_1d)
print(empty_array_1d.shape)

[0. 0. 0. 0. 0.]
(5,)


In [31]:
empty_array_2d = np.zeros((2, 5))
print(empty_array_2d)
print(empty_array_2d.shape)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
(2, 5)


In [32]:
empty_array_2d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
empty_array_plus_one = empty_array_2d + 1
empty_array_plus_one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
random_array = np.random.random((2, 5))
random_array

array([[0.64027372, 0.01032324, 0.874547  , 0.86762792, 0.416399  ],
       [0.98012749, 0.8710709 , 0.4855941 , 0.25532109, 0.60197282]])

In [35]:
# array 체크해보기
random_array.dtype

dtype('float64')

In [36]:
random_array.astype('float32')

array([[0.64027375, 0.01032324, 0.874547  , 0.8676279 , 0.416399  ],
       [0.9801275 , 0.8710709 , 0.4855941 , 0.2553211 , 0.6019728 ]],
      dtype=float32)

In [37]:
random_array.shape

(2, 5)

In [38]:
# 기초 연산
empty_array_plus_one + random_array

array([[1.64027372, 1.01032324, 1.874547  , 1.86762792, 1.416399  ],
       [1.98012749, 1.8710709 , 1.4855941 , 1.25532109, 1.60197282]])

In [39]:
empty_array_plus_one == empty_array_plus_one

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [40]:
empty_array_plus_one == random_array

array([[False, False, False, False, False],
       [False, False, False, False, False]])

In [41]:
np.power(2, 10) # 2^10

1024

In [42]:
np.sin(0)

0.0

In [43]:
np.cos(0)

1.0

In [44]:
np.log(1)

0.0

In [45]:
np.log(10)

2.302585092994046

In [46]:
np.log(100)

4.605170185988092

In [47]:
random_array.sum()

6.003257274859953

In [48]:
random_array.min(), random_array.max()

(0.0103232402880582, 0.9801274884115577)

In [49]:
# 선택
array_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [50]:
# row
array_2d[0, :]

array([1, 2, 3, 4, 5])

In [51]:
# column
array_2d[:, 0]

array([1, 6])

In [52]:
array_2d[:, 0:3]

array([[1, 2, 3],
       [6, 7, 8]])